name: Run slow TS tests
on:
  schedule:
    - cron: '0 6 * * 1,4' # 06:00 bi-weekly (mon, thu)
  workflow_dispatch:
jobs:
  slow:
    name: jsbt v0.4.5 large input tests
    uses: paulmillr/jsbt/.github/workflows/test-ts-slow.yml@857e7538fb14d48feaaa1dda889d8d4d10b9289d
    with:
      npm-task: test:slow
